export const POSTGREST_ERROR_CODES = Object.freeze({
  NO_ROWS_RETURNED: "PGRST116",
});

export const POSTGRES_ERROR_CODES = Object.freeze({
  UNIQUE_VIOLATION: "23505",
  FOREIGN_KEY_VIOLATION: "23503",
  NOT_NULL_VIOLATION: "23502",
  CHECK_VIOLATION: "23514",
  INVALID_TEXT_REPRESENTATION: "22P02",
});
