// Mock doctors database
export const doctorsDatabase = [
  {
    id: 1,
    name: "Dr. John Doe",
    specialty: "Cardiology",
    experience: "10 years",
    contact: "john.doe@hospital.com",
  },
  {
    id: 2,
    name: "Dr. Jane Smith",
    specialty: "Neurology",
    experience: "8 years",
    contact: "jane.smith@hospital.com",
  },
  {
    id: 3,
    name: "Dr. Michael Johnson",
    specialty: "Orthopedics",
    experience: "12 years",
    contact: "michael.johnson@hospital.com",
  },
  {
    id: 4,
    name: "Dr. Emily Davis",
    specialty: "Pediatrics",
    experience: "6 years",
    contact: "emily.davis@hospital.com",
  },
  {
    id: 5,
    name: "Dr. Robert Wilson",
    specialty: "Dermatology",
    experience: "15 years",
    contact: "robert.wilson@hospital.com",
  },
  {
    id: 6,
    name: "Dr. Olivia Martinez",
    specialty: "Endocrinology",
    experience: "9 years",
    contact: "olivia.martinez@hospital.com",
  },
  {
    id: 7,
    name: "Dr. William Brown",
    specialty: "Gastroenterology",
    experience: "11 years",
    contact: "william.brown@hospital.com",
  },
  {
    id: 8,
    name: "Dr. Sophia Lee",
    specialty: "Pulmonology",
    experience: "7 years",
    contact: "sophia.lee@hospital.com",
  },
  {
    id: 9,
    name: "Dr. Daniel Turner",
    specialty: "Rheumatology",
    experience: "14 years",
    contact: "daniel.turner@hospital.com",
  },
  {
    id: 11,
    name: "Dr. Sophia Garcia",
    specialty: "Nephrology",
    experience: "13 years",
    contact: "sophia.garcia@hospital.com",
  },
  {
    id: 12,
    name: "Dr. Ethan Miller",
    specialty: "Urology",
    experience: "8 years",
    contact: "ethan.miller@hospital.com",
  },
  {
    id: 13,
    name: "Dr. Isabella Rodriguez",
    specialty: "Hematology",
    experience: "12 years",
    contact: "isabella.rodriguez@hospital.com",
  },
  {
    id: 14,
    name: "Dr. Liam Martinez",
    specialty: "Infectious Diseases",
    experience: "10 years",
    contact: "liam.martinez@hospital.com",
  },
  {
    id: 15,
    name: "Dr. Ava Lopez",
    specialty: "Allergy and Immunology",
    experience: "7 years",
    contact: "ava.lopez@hospital.com",
  },
  {
    id: 16,
    name: "Dr. Noah Gonzalez",
    specialty: "Physical Medicine and Rehabilitation",
    experience: "14 years",
    contact: "noah.gonzalez@hospital.com",
  },
  {
    id: 17,
    name: "Dr. Mia Perez",
    specialty: "Emergency Medicine",
    experience: "9 years",
    contact: "mia.perez@hospital.com",
  },
  {
    id: 18,
    name: "Dr. James Torres",
    specialty: "Pathology",
    experience: "16 years",
    contact: "james.torres@hospital.com",
  },
  {
    id: 19,
    name: "Dr. Charlotte Sanchez",
    specialty: "Radiology",
    experience: "11 years",
    contact: "charlotte.sanchez@hospital.com",
  },
  {
    id: 20,
    name: "Dr. Benjamin Ramirez",
    specialty: "Anesthesiology",
    experience: "15 years",
    contact: "benjamin.ramirez@hospital.com",
  },
];
